POST http://localhost:8000/products
Content-Type: application/json

{
   "name": "My Product",
    "price": 100
}

### GET ONE

GET http://localhost:8000/products/87b34487-0534-42c0-8582-41359f512f48
Content-Type: application/json

### GET ALL
GET http://localhost:8000/products
Content-Type: application/json



### UPDATE
PUT http://localhost:8000/products/87b34487-0534-42c0-8582-41359f512f48
Content-Type: application/json

{
   "name": "My Product updated",
    "price": 1000
}

### DELETE
DELETE  http://localhost:8000/products/87b34487-0534-42c0-8582-41359f512f48
Content-Type: application/json