### GET WEATHER BY CEP
GET http://localhost:8080/weather/cep/11111111 HTTP/1.1
Host: localhost:8000
Content-Type: application/json

### VIA CEP
GET https://viacep.com.br/ws/11111111/json/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json