version: '3'

services:
  servicea:
    container_name: service-a-challenge
    build:
      context: service-a/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # REST
  serviceb:
    container_name: service-b-challenge
    build:
      context: ./service-b/.
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # REST

