version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  migrate:
    image: migrate/migrate
    depends_on:
      - mysql
    volumes:
      - ./internal/infra/database/migrations:/database
    command:
      [ "-path", "/database", "-database",  "mysql://root:root@tcp(mysql:3306)/orders", "up"]
      

  challenge:
    container_name: challenge
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
      DB_HOST: mysql
    ports:
      - "8000:8000" # REST
      - "8080:8080" # GraphQL
      - "50051:50051" # gRPC
    depends_on:
      - mysql
      - rabbitmq

